#! /bin/sh

# visp
# (c) Federico Churca-Torrusio 2016 <fchurca@fchurca.com.ar>
# See LICENSE for BSD 3-clause license

#  Open vim with a SCRATCH buffer and a connected Slimv, almost IDE-like
# All arguments will be passed on to vim (assumed to be files)

## Dependencies:
# vim
# slimv
# tmux or screen (optional)
# byobu (optional)
# gvim (optional)
# xterm (optional)

## Precedence order: (TODO: make configurable)
# * If running inside an interactive terminal (test -t 0):
#  * Running inside an existing screen, tmux, or other screen-ish will rely on
#    Slimv to start the server inside the same screen-ish if necessary
#  * Else, if byobu, screen, or tmux are available, start vim inside it
# * Else, we may be in an X11 session (test -n "$DISPLAY")
#  * If gvim exists, use it instead of vim. Slimv will try to start an xterm
#    for the server if necessary
#  * Else, rerun visp inside of an xterm, which is assumed to exist
# * Else, run vim as-is and pray.

# For Slimv by Tamas Kovaks, see:
# http://www.vim.org/scripts/script.php?script_id=2531

command_exists () {
	which "$1" >/dev/null
	return $?
}

eecho () {
	echo "$1" >&2
}

VISP_PRE=''
VISP_POST=''

# Tell Vim to call SlimvQuitRepl() on exit
# TODO: Make optional. Patch Slimv?
# FIXME: If two visps have their vims connected to the same swank, it may die
# as soon as the first visp exits
VISP_PRE="$VISP_PRE -c 'autocmd VimLeave * call SlimvQuitRepl()'"

# Avoid creating a separate SCRATCH buffer if no file given
[ -z "$1" ] && VISP_CREATE_SCRATCH='' || VISP_CREATE_SCRATCH=' '
[ -n "$VISP_CREATE_SCRATCH" ] && VISP_PRE="$VISP_PRE -c 'new'"

# Create a SCRATCH buffer
VISP_PRE="$VISP_PRE -c 'file SCRATCH' -c 'set filetype=lisp' "
if [ -n "$VISP_CREATE_SCRATCH" ]; then
	VISP_PRE="$VISP_PRE -c 'wincmd w'"
	VISP_PRE="$VISP_PRE -c 'wincmd o'"
else
	VISP_POST="-c 'wincmd w'"
fi
VISP_PRE="$VISP_PRE -c 'wincmd v'"


VIM_ARGUMENTS="$@ $VISP_PRE -c 'execute SlimvConnectServer()' $VISP_POST"
VISP_COMMAND="vim $VIM_ARGUMENTS"

# or shell-interactive-p nested-visp-p
if [ -t 0 ]; then
	if [ -n "$TMUX" ]; then
		eecho "Trying to start visp inside of an existing tmux session"
	elif [ -n "$STY" ]; then
		eecho "Trying to start visp inside of an existing screen session"
	elif [ -n "$SCREEN" ]; then
		eecho "Trying to start visp inside of an existing screen-ish"
	elif [ -z "$VISP_NESTED" ]; then
		if command_exists byobu; then
			eecho "Trying to nest another visp inside of a new byobu session"
			VISP_NESTED=1
			. "$HOME/.byobu/backend"
			case "$BYOBU_BACKEND" in
				tmux)
					VISP_COMMAND="byobu new-session -n visp '$0 $@'"
					;;
				screen|*)
					VISP_COMMAND="byobu $0 $@"
					;;
			esac
		elif command_exists screen; then
			eecho "Trying to nest another visp inside of a new screen session"
			VISP_NESTED=1
			VISP_COMMAND="screen $0 $@"
		elif command_exists tmux; then
			eecho "Trying to nest another visp inside of a new tmux session"
			VISP_NESTED=1
			VISP_COMMAND="tmux -c $0 $@"
		fi
	fi
	# inside-x11-p
elif [ -n "$DISPLAY" ]; then
	if command_exists gvim; then
		eecho "Trying to start visp in a gvim; Slimv may try to start an xterm"
		VISP_COMMAND="g$VISP_COMMAND"
	elif [ -z "$VISP_NESTED" ]; then
		eecho "Trying to nest another visp in xterm"
		VISP_NESTED=1
		export VISP_NESTED
		VISP_COMMAND="xterm -e $0 $@"
	fi
else
	# nothing-available
	eecho "Trying to start visp by itself. Slimv may try to start an xterm, but it may not succeed!"
fi

eecho "Will run ${VISP_COMMAND}"

eval "$VISP_COMMAND"
exit $?

